@startditaa
+------------------------------------------------------------+
| FICHA DE PROCESO                                           |
+------------------------------------------------------------+
| Descripcion                                                |
+------------------+------------------------+----------------+
| Entrada          | Descripcion del        | Salida         |
|                  | proceso                |                |
+------------------+------------------------+----------------+
@endditaa