@startditaa
+------------------------------------------------------------+
| FICHA DE FLUJO DE DATO                                     |
+------------------------------------------------------------+
| Descripcion                                                |
+------------------------------------------------------------+
| Estructura de datos que viaja con el flujo                 |
+------------------+-----------+-----------------------------+
| Fuente           |   -->     | Destino                     |
+------------------+-----------+-----------------------------+
| Volumen                                                    |
+------------------------------------------------------------+
@endditaa