@startditaa
+------------------------------------------------------------+
| FICHA DE ALMACEN                                           |
+------------------------------------------------------------+
| Descripcion                                                |
+----------------------------+-------------------------------+
| Flujo de datos             | Flujo de datos                |
| entrantes                  | salientes                     |
+----------------------------+-------------------------------+
@endditaa