@startditaa
+------------------------------------------------------------+
| FICHA DE ENTIDAD                                           |
+------------------------------------------------------------+
| Descripcion                                                |
+------------------+------------------------+----------------+
| Entrada          | Descripcion de la      | Salida         |
|                  | Entidad                |                |
+------------------+------------------------+----------------+
@endditaa