@startditaa
+------------------------------------------------------------+
| FICHA DE DATO ELEMENTAL                                    |
+------------------------------------------------------------+
| Descripcion                                                |
+------------------+-----------------------------------------+
| Alias            | Longitud                                |
+------------------+-----------------------------------------+
| Valores permitidos                                         |
+------------------------------------------------------------+
@endditaa